# Site settings
title: Hannah Birch
email: birch.hannah@gmail.com
description: My content strategy, editing, and production work for the MTA, ProPublica, The Seattle Times, and more.
url: "https://hannahsbirch.com" # the base hostname & protocol for your site
twitter_username: hannahsbirch
github_username:  hannah-birch
image: /assets/img/default-og-image-1200x630.png

permalink: /:year-:month-:day/:title:output_ext

# Build settings
markdown: kramdown
