# Site settings
title: Hannah Birch
email: birch.hannah@gmail.com
description: My content strategy, editing, and production work for the MTA, ProPublica, The Seattle Times, and more.
url: "https://hannah-birch.github.io" # the base hostname & protocol for your site
twitter_username: hannahsbirch
github_username:  hannah-birch

# Build settings
markdown: kramdown
