# Site settings
title: Hannah Birch
email: birch.hannah@gmail.com
description: Mostly harmless Web producer for ProPublica. Stealth copy editor, ace cat herder.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hannahsbirch.com/" # the base hostname & protocol for your site
twitter_username: hannahsbirch
github_username:  hannah-birch

# Build settings
markdown: kramdown
